# Generated by Django 4.2.27 on 2026-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('scheduling', '0002_appointment_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='providers', to='profiles.patientprofile'),
        ),
    ]
