# Generated by Django 4.2.27 on 2026-04-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_provider_patients"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreCheckInRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=255)),
                ("emergency_contact_phone", models.CharField(blank=True, max_length=20)),
                ("symptoms", models.TextField(blank=True)),
                ("current_medications", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("insurance_provider", models.CharField(blank=True, max_length=255)),
                ("insurance_member_id", models.CharField(blank=True, max_length=100)),
                ("accommodation_notes", models.TextField(blank=True)),
                ("additional_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_check_in_record",
                        to="scheduling.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
