# Generated by Django 4.2.27 on 2026-04-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_precheckinrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='availability_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='scheduling.availabilityslot'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='requested_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to='scheduling.availabilityslot'),
        ),
    ]
